name: Sample Application CI Demo
on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:  
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: npm install
      - run: yarn build
      - run: yarn start 3000 &

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: 'ofindley/sample-ci-webdriverio-test'
          ref: 'main'
          start: npm install
          start: npm run test
          wait-on: 'http://localhost:3000'

