name: Sample Application CI Demo
on:
  push:
    branches:
      - dev
      - qa
      - master

jobs:  
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Application code
        uses: actions/checkout@v2
      - name: Install Application dependencies
        run: npm install
      - name: Build Application code
        run: yarn build
      - name: Start Application
        run: yarn start 3000 &
      - name: Get public url
        run: npm i -g localtunnel; lt --port 3000 --subdomain ciexample121 &> url.txt&
      - name: Check if file exist
        run: ls
      - name: Read url.txt
        id: url
        uses: juliangruber/read-file-action@v1
        with:
          path: ./url.txt
      - name: Echo url.txt
        run: echo "${{ steps.url.outputs.content }}"
      - name: Set baseurl
        run: echo '::set-output name=BASE_URL::$(cat url.txt | egrep -o "(http|https)://[a-zA-Z0-9./?=_%:-]*")'
        id: random-base-url
      - name: Get baseurl
        run: echo "The url is ${{ steps.random-base-url.outputs.BASE_URL }}"
      - name: Check out Test Automation code
        uses: actions/checkout@v2
        with:
          repository: 'ofindley/sample-ci-webdriverio-test'
          ref: 'main'
      - name: Install Test dependencies
        uses: docker://buildkite/puppeteer:latest
        with:
            args: npm install
      - name: Execute Tests
        uses: docker://buildkite/puppeteer:latest
        with:
            args: npm test