name: Sample Application CI Demo
on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:  
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Application code
        uses: actions/checkout@v2
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.0.0
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: 'team_Ohbt6zX5TqMSL5dvSWcnhOWm'
          vercel_project_id: 'prj_zwVXa38hjQb2JtErhJRhJa3fqIdx'
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
      - name: Check out Test Automation code
        uses: actions/checkout@v2
        with:
          repository: 'ofindley/sample-ci-webdriverio-test'
          ref: 'main'
      - name: Install Test dependencies
        uses: docker://buildkite/puppeteer:latest
        with:
            args: npm install
      - name: Execute Tests
        env:
          URL: ${{ env.base_url }}
        uses: docker://buildkite/puppeteer:latest
        with:
            args: npm test